[keyboard]
bindings = [
  { key = "V",        mods = "Option|Shift", action = "Paste" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "P",        mods = "Option", action = "Paste" },
  { key = "C",        mods = "Option|Shift", action = "Copy" },
  { key = "J", mods = "Option", action = "ScrollLineDown" },
  { key = "K", mods = "Option", action = "ScrollLineUp" },
  { key = "Space", mods = "Option", action = "ToggleViMode" },
  { key = "S", mods = "Option",action = "SearchForward" },
  { key = "R", mods = "Option",action = "SearchBackward" },
]
