#!/bin/sh

# load sxhkd for keybinds
pgrep sxhkd || sxhkd -c "$HOME/.config/dk/sxhkdrc" &

logfile="$HOME/.dklog"
{ # compound command to redirect all output

	# workspace settings
	dkcmd set numws=8
	dkcmd set ws=_ apply layout=tile master=1 stack=3 gap=4 msplit=0.6 ssplit=0.4
	dkcmd set \
		ws=1  name="life" \
		ws=2  name="study" \
		ws=3  name="work" \
		ws=4  name="shell" \
		ws=5  name="shows" \
		ws=6  name="gaming" \
		ws=7  name="generic" \
		ws=8  name="monitor" \

    # static workspaces assigned to monitors
	mon1='eDP'
	mon2='HDMI-A-0'
	dkcmd set static_ws=true \
		ws=1  mon=$mon2 \
		ws=2  mon=$mon2 \
		ws=3  mon=$mon2 \
		ws=4  mon=$mon2 \
		ws=5  mon=$mon2 \
		ws=6  mon=$mon2 \
		ws=7  mon=$mon2 \
		ws=8  mon=$mon1 \

	# minimum width/height for resizing, and minimum allowed on-screen when moving
	dkcmd set win_minwh=50 win_minxy=10
	# mantain gaps and borders in single window layouts
	dkcmd set smart_gap=false smart_border=false
	# define mouse mod and move/resize buttons
	dkcmd set mouse mod=super move=button3 resize=button1
	# obey motif border hints on windows that draw their own
	dkcmd set obey_motif=true

    # borders
	dkcmd set border width=8 outer_width=0 \
		colour \
		focus='#4ad66d' \
		unfocus='#ffffff' \
		urgent='#ee5555' \
		outer_focus='#4ad66d' \
		outer_unfocus='#ffffff' \
		outer_urgent='#222222'

    # save from being grabbed by another ws while opening
	dkcmd rule class="^codium$" ignore_msg=true
	dkcmd rule class="^thorium-browser$" ignore_msg=true
	dkcmd rule class="^cutter$" ignore_msg=true

	# define terminals for window swallowing
	dkcmd rule class="^(st|st-256color|urxvt|kitty|alacritty|xterm|xterm-256color)$" terminal=true

	# window rules
    # dkcmd rule class="^$" ws=3

	# focus window and workspace on opening
	# dkcmd rule class="^$" ws=1 focus=true
    
    # open these floating
	# dkcmd rule class="^$" float=true

	# apply current rules
	dkcmd rule apply '*'

} >> "$logfile" 2>&1
